version: '3'
services: 
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes: 
      - /app/node_modules
      - ./client:/app
    environment: 
      REACT_APP_API_HOST: http://localhost:3001/graphql
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - 3001:3001
    depends_on:
      - mongo
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      NODE_ENV: development
      PASSWORD_SALT: mysupersecret
      TOKEN_SECRET: MY_SECRET_KEY